### ISSUE TITLE
I have to change channel on the box to be able to stream

### ISSUE THREAD

**Issue by fozter** [joeyloman/openetv#6]
Every time i want to change to another channel i have to go into the box webui and switch to that channel. After that i go to the openetv webui and choose that channel in the drop down menu.
Is it possible to add some kind of switch command in the script?

I can do it with wget but it would be nice if it could be an option in the openetv-webui.

wget -q -O - http://"box-ip"/web/zap?sRef="channel ref"

**Comment by joeyloman** [comment]
I have seen this behaviour before when the box is turned ON instead of standby. Could that be the case? In that case the box is using your (single) tuner and cannot use it for openetv. You can add a second tuner to the box. Then he always has a free tuner to use and you don't have to switch channels through the box or webui. Or fix this in your enigma configuration of the box?
